hostname = glados.rocks, m.sw16.icu

# 机场签到Cookie版
https:\/\/m\.sw16\.icu url script-request-header https://raw.githubusercontent.com/evilbutcher/Quantumult_X/master/check_in/glados/checkincookie_env.js
# GLaDOS
https:\/\/glados\.rocks\/api\/user\/checkin url script-request-header https://raw.githubusercontent.com/evilbutcher/Quantumult_X/master/check_in/glados/glados.js
